//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace KNB.Demo {
    
    
    public partial class General {
        
        /// <summary>
        /// TopBiggestAwards1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KNB.Demo.TopBiggestAwards TopBiggestAwards1;
        
        /// <summary>
        /// TopRecentAwards1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::KNB.Demo.TopRecentAwards TopRecentAwards1;
    }
}
